# Generated by Django 6.0 on 2026-03-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cabinet_user_cabinet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cabinet',
        ),
        migrations.AddField(
            model_name='user',
            name='cabinets',
            field=models.ManyToManyField(blank=True, related_name='Comptables', to='users.cabinet', verbose_name='Cabinets'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_collaborateur',
            field=models.BooleanField(default=False, help_text='Collaborateur du Cabinet GCL'),
        ),
    ]
