# Generated by Django 6.0 on 2025-12-29 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('siren', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True, verbose_name='SIREN')),
                ('nom_entreprise', models.CharField(max_length=255, verbose_name='Nom entreprise')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archivé')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireClient',
            fields=[
                ('entreprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='questionnaire_client', serialize=False, to='questionnaires.entreprise')),
                ('logiciel_facturation', models.BooleanField(default=False)),
                ('logiciel_facturation_nom', models.CharField(blank=True, max_length=255)),
                ('factures_format_electronique', models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non'), ('nsp', 'Je ne sais pas')], max_length=10)),
                ('logiciel_devis', models.BooleanField(default=False)),
                ('logiciel_devis_nom', models.CharField(blank=True, max_length=255)),
                ('caisse_enregistreuse', models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non'), ('na', 'Non applicable')], max_length=10)),
                ('caisse_enregistreuse_nom', models.CharField(blank=True, max_length=255)),
                ('caisse_certifiee', models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non'), ('nsp', 'Je ne sais pas')], max_length=10)),
                ('plateforme_agreee', models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non'), ('nsp', 'Je ne sais pas')], max_length=10)),
                ('plateforme_agreee_nom', models.CharField(blank=True, max_length=255)),
                ('gestion_future', models.CharField(blank=True, choices=[('interne', 'Gérer en interne avec accompagnement'), ('deleguer', 'Déléguer au cabinet'), ('nsp', 'Je ne sais pas, besoin de conseils')], max_length=20)),
                ('aisance_outils', models.CharField(blank=True, choices=[('tres_aise', "Très à l'aise"), ('moyen', 'Moyen'), ('pas_aise', "Pas du tout à l'aise")], max_length=20)),
                ('reception_factures_achats', models.CharField(blank=True, choices=[('papier', 'Principalement par courrier papier'), ('email', 'Principalement par email (PDF)'), ('mixte', 'Mix papier/email'), ('plateforme', 'Via plateforme dématérialisée'), ('autre', 'Autre')], max_length=20)),
                ('reception_achats_autre', models.CharField(blank=True, max_length=255)),
                ('envoi_factures_ventes', models.CharField(blank=True, choices=[('papier', 'Principalement par courrier papier'), ('email', 'Principalement par email (PDF)'), ('mixte', 'Mix papier/email'), ('plateforme', 'Via plateforme dématérialisée'), ('autre', 'Autre')], max_length=20)),
                ('envoi_ventes_autre', models.CharField(blank=True, max_length=255)),
                ('conservation_factures', models.CharField(blank=True, choices=[('papier', 'Classement papier uniquement'), ('electronique', 'Archivage électronique uniquement'), ('mixte', 'Mix papier + électronique'), ('cabinet', 'Confié au cabinet comptable')], max_length=20)),
                ('accompagnement_souhaite', models.JSONField(blank=True, default=list, help_text="Liste des types d'accompagnement")),
                ('accompagnement_autre', models.CharField(blank=True, max_length=255)),
                ('commentaires', models.TextField(blank=True)),
                ('date_completion', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cookies_consent_date', models.DateTimeField(blank=True, help_text='Date acceptation cookies', null=True)),
            ],
            options={
                'verbose_name': 'Questionnaire Client',
                'verbose_name_plural': 'Questionnaires Clients',
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireCollaborateur',
            fields=[
                ('entreprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='questionnaire_collaborateur', serialize=False, to='questionnaires.entreprise')),
                ('assujettie_tva', models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non'), ('doute', "J'ai un doute")], max_length=10)),
                ('code_ape', models.CharField(blank=True, max_length=10)),
                ('activite_precise', models.TextField(blank=True)),
                ('taille_entreprise', models.CharField(blank=True, choices=[('tpe_pme', 'TPE/PME'), ('eti', 'ETI'), ('grande', 'Grande entreprise')], max_length=20)),
                ('regime_tva', models.CharField(blank=True, choices=[('franchise', 'Franchise en base'), ('reel_simplifie', 'Réel simplifié'), ('reel_trimestriel', 'Réel trimestriel'), ('reel_mensuel', 'Réel mensuel')], max_length=20)),
                ('activite_exoneree_tva', models.CharField(blank=True, choices=[('sante', 'Prestations santé'), ('enseignement', 'Enseignement et formation'), ('immobilier', 'Opérations immobilières'), ('asso', 'Associations à but non lucratif'), ('banque', 'Opérations bancaires et financières'), ('assurance', "Opérations d'assurance"), ('mixte', "Activité mixte ou n'exerce pas dans ces secteurs")], max_length=20)),
                ('plateforme_agreee', models.BooleanField(default=False)),
                ('plateforme_agreee_nom', models.CharField(blank=True, max_length=255)),
                ('nb_factures_ventes', models.CharField(blank=True, choices=[('moins_50', 'Moins de 50'), ('50_200', 'Entre 50 et 200'), ('200_1000', 'Entre 200 et 1000'), ('1000_5000', 'Entre 1000 et 5000'), ('plus_5000', 'Plus de 5000'), ('na', 'N/A')], max_length=20)),
                ('nb_clients_actifs', models.CharField(blank=True, choices=[('moins_10', 'Moins de 10'), ('10_50', 'Entre 10 et 50'), ('50_200', 'Entre 50 et 200'), ('plus_200', 'Plus de 200'), ('na', 'N/A')], max_length=20)),
                ('vente_btob_domestique', models.BooleanField(default=False)),
                ('vente_btob_export', models.BooleanField(default=False)),
                ('vente_btoc_facture', models.BooleanField(default=False)),
                ('vente_btoc_caisse', models.BooleanField(default=False)),
                ('nb_factures_achats', models.CharField(blank=True, choices=[('moins_50', 'Moins de 50'), ('50_200', 'Entre 50 et 200'), ('200_1000', 'Entre 200 et 1000'), ('1000_5000', 'Entre 1000 et 5000'), ('plus_5000', 'Plus de 5000'), ('na', 'N/A')], max_length=20)),
                ('nb_fournisseurs_actifs', models.CharField(blank=True, choices=[('moins_10', 'Moins de 10'), ('10_50', 'Entre 10 et 50'), ('50_200', 'Entre 50 et 200'), ('plus_200', 'Plus de 200'), ('na', 'N/A')], max_length=20)),
                ('achat_btob_domestique', models.BooleanField(default=False)),
                ('achat_btob_intracommunautaire', models.BooleanField(default=False)),
                ('achat_btob_hors_ue', models.BooleanField(default=False)),
                ('commentaires', models.TextField(blank=True)),
                ('date_completion', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cookies_consent_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Questionnaire Collaborateur',
                'verbose_name_plural': 'Questionnaires Collaborateurs',
            },
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['siren'], name='questionnai_siren_20ddd2_idx'),
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['nom_entreprise'], name='questionnai_nom_ent_bd6177_idx'),
        ),
        migrations.AddField(
            model_name='questionnaireclient',
            name='modifie_par_collaborateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaires_client_modifies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionnairecollaborateur',
            name='collaborateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires_crees', to=settings.AUTH_USER_MODEL),
        ),
    ]
