# Generated by Django 6.0 on 2025-12-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireclient',
            name='aisance_outils',
            field=models.CharField(blank=True, choices=[('very_comfortable', "Très à l'aise"), ('medium', 'Moyen'), ('not_comfortable', "Pas du tout à l'aise")], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionnaireclient',
            name='caisse_certifiee',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('dont_know', 'Je ne sais pas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionnaireclient',
            name='caisse_enregistreuse',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('not_applicable', 'Non applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionnaireclient',
            name='conservation_factures',
            field=models.CharField(blank=True, choices=[('paper', 'Classement papier uniquement'), ('electronic', 'Archivage électronique uniquement'), ('mixed', 'Mix papier + électronique'), ('accounting_firm', 'Confié au cabinet comptable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionnaireclient',
            name='envoi_factures_ventes',
            field=models.CharField(blank=True, choices=[('paper', 'Principalement par courrier papier'), ('email', 'Principalement par email (PDF)'), ('mixed', 'Mix papier/email'), ('platform', 'Via plateforme dématérialisée'), ('other', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionnaireclient',
            name='factures_format_electronique',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('dont_know', 'Je ne sais pas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionnaireclient',
            name='gestion_future',
            field=models.CharField(blank=True, choices=[('internal', 'Gérer en interne avec accompagnement'), ('delegate', 'Déléguer au cabinet'), ('dont_know', 'Je ne sais pas, besoin de conseils')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionnaireclient',
            name='plateforme_agreee',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('dont_know', 'Je ne sais pas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionnaireclient',
            name='reception_factures_achats',
            field=models.CharField(blank=True, choices=[('paper', 'Principalement par courrier papier'), ('email', 'Principalement par email (PDF)'), ('mixed', 'Mix papier/email'), ('platform', 'Via plateforme dématérialisée'), ('other', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionnairecollaborateur',
            name='activite_exoneree_tva',
            field=models.CharField(blank=True, choices=[('health', 'Prestations santé'), ('education', 'Enseignement et formation'), ('real_estate', 'Opérations immobilières'), ('nonprofit', 'Associations à but non lucratif'), ('banking', 'Opérations bancaires et financières'), ('insurance', "Opérations d'assurance"), ('mixed', "Activité mixte ou n'exerce pas dans ces secteurs")], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionnairecollaborateur',
            name='assujettie_tva',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('unsure', "J'ai un doute")], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionnairecollaborateur',
            name='nb_clients_actifs',
            field=models.CharField(blank=True, choices=[('less_than_10', 'Moins de 10'), ('between_10_50', 'Entre 10 et 50'), ('between_50_200', 'Entre 50 et 200'), ('more_than_200', 'Plus de 200'), ('not_applicable', 'N/A')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionnairecollaborateur',
            name='nb_factures_achats',
            field=models.CharField(blank=True, choices=[('less_than_50', 'Moins de 50'), ('between_50_200', 'Entre 50 et 200'), ('between_200_1000', 'Entre 200 et 1000'), ('between_1000_5000', 'Entre 1000 et 5000'), ('more_than_5000', 'Plus de 5000'), ('not_applicable', 'N/A')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionnairecollaborateur',
            name='nb_factures_ventes',
            field=models.CharField(blank=True, choices=[('less_than_50', 'Moins de 50'), ('between_50_200', 'Entre 50 et 200'), ('between_200_1000', 'Entre 200 et 1000'), ('between_1000_5000', 'Entre 1000 et 5000'), ('more_than_5000', 'Plus de 5000'), ('not_applicable', 'N/A')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionnairecollaborateur',
            name='nb_fournisseurs_actifs',
            field=models.CharField(blank=True, choices=[('less_than_10', 'Moins de 10'), ('between_10_50', 'Entre 10 et 50'), ('between_50_200', 'Entre 50 et 200'), ('more_than_200', 'Plus de 200'), ('not_applicable', 'N/A')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionnairecollaborateur',
            name='regime_tva',
            field=models.CharField(blank=True, choices=[('franchise', 'Franchise en base'), ('simplified_real', 'Réel simplifié'), ('quarterly_real', 'Réel trimestriel'), ('monthly_real', 'Réel mensuel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionnairecollaborateur',
            name='taille_entreprise',
            field=models.CharField(blank=True, choices=[('small_medium', 'TPE/PME'), ('mid_sized', 'ETI'), ('large', 'Grande entreprise')], max_length=20),
        ),
    ]
