# Generated by Django 6.0 on 2026-02-22 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_alter_questionnaireclient_aisance_outils_and_more'),
        ('users', '0002_cabinet_user_cabinet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireclient',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaires_client', to='users.cabinet', verbose_name='Cabinet associé'),
        ),
        migrations.AddField(
            model_name='questionnaireclient',
            name='collaborateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaires_client_associes', to=settings.AUTH_USER_MODEL, verbose_name='Collaborateur associé'),
        ),
    ]
