"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import environ

import pymysql
pymysql.install_as_MySQLdb()

# Ignorer la vérification de version Django/MySQL
pymysql.version_info = (2, 2, 1, "final", 0)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialiser environ
env = environ.Env(
    DEBUG=(bool, False)
)

# Lire le fichier .env
environ.Env.read_env(str(BASE_DIR / '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])


# Application definition

INSTALLED_APPS = [
    'axes',  # Protection contre les attaques brute force (DOIT être avant django.contrib.admin)
    'users',
    'questionnaires',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',  # Protection brute force (DOIT être après AuthenticationMiddleware)
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Templates à la racine
        'APP_DIRS': True,  # Cherche aussi dans apps/templates/
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.context_processors.cabinet_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Database - Support SQLite (dev) et MySQL (prod)
if env('USE_MYSQL', default=False):
    # Production - MySQL
    DATABASES = {
        'default': {
            # 'ENGINE': 'django.db.backends.mysql',
            'ENGINE': env('DB_ENGINE'),
            'NAME': env('DB_NAME'),
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASSWORD'),
            'HOST': env('DB_HOST', default='localhost'),
            'PORT': env('DB_PORT', default='3306'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
            },
        }
    }
else:
    # Développement - SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Session configuration
SESSION_COOKIE_AGE = 14400  # 4 heures
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_SECURE = not DEBUG  # True si DEBUG=False
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# CSRF
CSRF_COOKIE_SECURE = not DEBUG  
CSRF_COOKIE_HTTPONLY = True

CSRF_TRUSTED_ORIGINS = [
    'http://diagnostic-GCL.sitesdemo.net',
    'https://diagnostic-GCL.sitesdemo.net',
]

# Cache (pour API INSEE - 24h)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 86400,  # 24h
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# API INSEE
INSEE_API_KEY = env('INSEE_API_KEY', default='')

# Login/Logout URLs
LOGIN_URL = '/collaborateur/login/'
LOGIN_REDIRECT_URL = '/collaborateur/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Django Axes - Protection contre les attaques brute force
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # Backend axes pour la protection brute force
    'django.contrib.auth.backends.ModelBackend',  # Backend par défaut de Django
]
AXES_FAILURE_LIMIT = 5  # Nombre max de tentatives échouées
AXES_COOLOFF_TIME = 1  # Temps de blocage en heures
AXES_LOCKOUT_PARAMETERS = [['username', 'ip_address']]  # Bloquer par combinaison user + IP
AXES_RESET_ON_SUCCESS = True  # Réinitialiser le compteur après connexion réussie
AXES_LOCKOUT_TEMPLATE = None  # Utiliser le template par défaut




# INFORMATIONS DU CABINET
CABINET_NAME = env('CABINET_NAME', default='Cabinet GCL')
CABINET_ADDRESS = env('CABINET_ADDRESS', default="58 bis rue de l'Ambassadeur - 95610 ERAGNY")
CABINET_EMAIL = env('CABINET_EMAIL', default='f.lecuyer@gcl.tm.fr')
CABINET_PHONE = env('CABINET_PHONE', default='01 39 09 49 20')